spring.application.name=backend

# PostgreSQL
# Local Docker default: localhost:5433/galaxy_atlas
# Render/Neon icin environment variable verilirse onu kullanir.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/galaxy_atlas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# NASA API
# Mobilde simdilik kullanmasak bile backend API tarafinda kalabilir.
nasa.api.key=${NASA_API_KEY:uYsD2U1Fzc7NSdGSONFM0JVydAT4FH8gSRwtuieT}

# Redis
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=redis

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}