spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/galaxy_atlas
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

nasa.api.key=uYsD2U1Fzc7NSdGSONFM0JVydAT4FH8gSRwtuieT
spring.datasource.url=jdbc:postgresql://ep-falling-smoke-aggipr1r.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_vD4rSoZ2MCKp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


