spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-falling-smoke-aggipr1r.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_vD4rSoZ2MCKp}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

nasa.api.key=${NASA_API_KEY:uYsD2U1Fzc7NSdGSONFM0JVydAT4FH8gSRwtuieT}