name: Galaxy Atlas CI

on:
  push:
    branches:
      - main
      - murat
      - berra
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    name: Backend Maven Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: galaxy_atlas
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d galaxy_atlas"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Give Maven wrapper permission
        run: chmod +x backend/mvnw

      - name: Build backend
        working-directory: backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/galaxy_atlas
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 12345
          SPRING_REDIS_HOST: localhost
          SPRING_REDIS_PORT: 6379
          SPRING_RABBITMQ_HOST: localhost
          SPRING_RABBITMQ_PORT: 5672
          SPRING_RABBITMQ_USERNAME: guest
          SPRING_RABBITMQ_PASSWORD: guest
        run: ./mvnw clean package -DskipTests